### ISSUE TITLE
CharacterState.setValue() 에 대한 문의

### ISSUE THREAD

**Issue by Loco-shoplive** [itssweetrain/shoplive#5]
```
_state.value = _state.value.copy(page = _state.value.page + 1, isPageLoading = true)
```

이렇게 copy를 해서 객체를 setValue 하는 코드가 많이 있더라구요. state 를 따로 두는 것보다 하나로 합치면 장점이 있나요? 아니면 단점이 있나요? 설명 부탁드립니다.

state관련 문제는 아닐진 몰라도 현재 error 발생했을때 state에 `isLoading = false` 에 대한 처리를 하지 않아 loading이 사라지지 않는 문제가 있습니다. (재현경로는 repository 구현 로직에 `throw Exception()`을 하면 테스트 가능합니다.)

**Comment by itssweetrain** [comment]
저는 보통 하나의 상태 객체를 사용하는 걸 선호하는 편인데 그 이유는 다음과 같습니다.

- 하나의 데이터에 필요한 모든 상태를 포함할 수 있어 UI에 대한 비즈니스 로직 처리가 편합니다.  
  - 위와 같이 페이지네이션에 관한 view logic 으로 page state 의 변경을 하고 진행 상태 및 오류 상태를 isPageLoading으로 함께 처리할 수 있습니다.
* UI 를 변경하는 코드가 분산되어 있지 않아 코드 분석이 편합니다. 
  - 예를 들어 page와 isPageLoading 값을 각각의 state로 분리하고 두 값 모두 변경해줘야한다면 구독을 처리하는 코드가 더 많아지게 됩니다. 또한 state 값이 많은 경우라면 관리 포인트들이 각각 생기는 것이기 때문에 실수를 할 가능성이 높습니다. 
state값을 전달하는 부분에서도 ui state 값은 모두 state라는 변수이름으로 객체를 가지고 있기에(위와 같은 예시에서는) ui state 값임을 명확히 할 수 있습니다. 
* 그리고 data class 를 사용하면 copy 함수를 사용할 수 있기에 원하는 필드값만 쉽게 변경할 수 있는 장점이 있습니다. 


하지만 단점도 있습니다. 
* 화면이 복잡해지는 경우 data class 에 필요한 프로퍼티가 비약적으로 늘어나게 됩니다. 

비교적 간단한 화면에는 하나씩 state를 관리하는 것이 좋고 view logic 이 복잡하게 들어가는 경우는 하나의 state 객체로 묶어서 관리하는 것이 좋을 것 같습니다. 

그리고 error가 발생했을 때 isLoading = false 처리를 하지 않고 로딩바를 그대로 보여주는 것은, 사용자에게 더 나은 경험을 줄 것이라고 생각합니다. 에러의 표현으로 로딩바를 표시하면 사용자에게 문제가 있음을 알릴 수 있고 데이터가 fetch 나 update가 되지 않고 있음을 미리 알려줄 수 있는 수단이 됩니다. 

위의 과제와 같은 경우에도 repository 단에 있는 함수를 구독했을 경우 에러가 나오는 경우일텐데 이 경우 데이터가 업데이트 되지 않았음을 유저에게 로딩바로 알려주는 것이 좋다 판단하여 노출하였습니다.

물론 특정 종류의 에러에 대한 처리가 필요하다면 상황에 맞게 처리해야 합니다. 예를 들어 새로 고침이나 팝업과 같이 어떤 대응이 필요한지에 따라 달라질 수 있습니다.
